# Generated by Django 5.2.5 on 2025-08-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('nit', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseInterval',
            fields=[
                ('interval_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='quoteAndBuildApp.phase')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='quoteAndBuildApp.project'),
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_first_quote', models.BooleanField()),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quoteAndBuildApp.phase')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMaterial',
            fields=[
                ('supplier_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='quoteAndBuildApp.material')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quoteAndBuildApp.supplier')),
            ],
            options={
                'unique_together': {('nit', 'material_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='quoteAndBuildApp.client')),
            ],
            options={
                'unique_together': {('cedula', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.client')),
            ],
            options={
                'unique_together': {('cedula', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='PhaseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_estimated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_estimated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='quoteAndBuildApp.material')),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quoteAndBuildApp.phase')),
            ],
            options={
                'unique_together': {('phase_id', 'material_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='quoteAndBuildApp.client')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='quoteAndBuildApp.project')),
            ],
            options={
                'unique_together': {('cedula', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSupplierMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_materials', to='quoteAndBuildApp.quotes')),
                ('supplier_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quoteAndBuildApp.suppliermaterial')),
            ],
            options={
                'unique_together': {('quote_id', 'supplier_material_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.supplier')),
            ],
            options={
                'unique_together': {('nit', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='QuoteWorker',
            fields=[
                ('quote_worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='quoteAndBuildApp.quotes')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quoteAndBuildApp.worker')),
            ],
            options={
                'unique_together': {('quote_id', 'cedula')},
            },
        ),
        migrations.CreateModel(
            name='WorkerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.worker')),
            ],
            options={
                'unique_together': {('cedula', 'phone')},
            },
        ),
    ]
