# Generated by Django 5.2.5 on 2025-08-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('nit', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='quoteAndBuildApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='quoteAndBuildApp.phase')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_estimated', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity_estimated', models.DecimalField(decimal_places=2, max_digits=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.material')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.phase')),
            ],
            options={
                'unique_together': {('phase', 'material')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='phases',
            field=models.ManyToManyField(through='quoteAndBuildApp.PhaseMaterial', to='quoteAndBuildApp.phase'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=160)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('clients', models.ManyToManyField(through='quoteAndBuildApp.ClientProject', to='quoteAndBuildApp.client')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='quoteAndBuildApp.project'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.project'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_first_quote', models.BooleanField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quoteAndBuildApp.phase')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.quote')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'material')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSupplierMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.quote')),
                ('supplierMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.suppliermaterial')),
            ],
            options={
                'unique_together': {('quote', 'supplierMaterial')},
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='materials',
            field=models.ManyToManyField(through='quoteAndBuildApp.QuoteSupplierMaterial', to='quoteAndBuildApp.suppliermaterial'),
        ),
        migrations.AddField(
            model_name='material',
            name='providers',
            field=models.ManyToManyField(through='quoteAndBuildApp.SupplierMaterial', to='quoteAndBuildApp.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('quotes', models.ManyToManyField(through='quoteAndBuildApp.QuoteWorker', to='quoteAndBuildApp.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quoteworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteAndBuildApp.worker'),
        ),
        migrations.CreateModel(
            name='WorkerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='quoteAndBuildApp.worker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientproject',
            unique_together={('client', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='quoteworker',
            unique_together={('quote', 'worker')},
        ),
    ]
