# Generated by Django 5.2.5 on 2025-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='phasematerial',
            name='quantity_estimated',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='phasematerial',
            name='unit_price_estimated',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='quotesuppliermaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='quotesuppliermaterial',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='quotesuppliermaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='suppliermaterial',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
