# Generated by Django 5.2.5 on 2025-09-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotesuppliermaterial',
            unique_together=set(),
        ),
    ]
