# Generated by Django 5.2.5 on 2025-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0002_alter_quotesuppliermaterial_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10),
        ),
    ]
