# Generated by Django 5.2.5 on 2025-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0004_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
