# Generated by Django 5.2.5 on 2025-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0005_phase_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseinterval',
            name='is_planning_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
