# Generated by Django 5.2.5 on 2025-09-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0006_phaseinterval_is_planning_phase_alter_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='duration',
        ),
    ]
