# Generated by Django 5.2.5 on 2025-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteAndBuildApp', '0007_remove_phase_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed')], default='inprogress', max_length=20),
        ),
        migrations.AlterField(
            model_name='phaseinterval',
            name='is_planning_phase',
            field=models.BooleanField(default=False, help_text='Indicates if this error is for the planning Phase'),
        ),
    ]
